### ISSUE TITLE
LAPIS v1 rises a 502 Bad Gateway

### ISSUE THREAD

**Issue by jpflorido** [GenSpectrum/LAPIS#825]
Hi,
I'm trying to use LAPIS v1 with the following query:
https://lapis.cov-spectrum.org/open/v1/sample/aggregated?fields=pangoLineage
but a "502 Bad Gateway" is raised.

Not sure if LAPIS v1 has been discontinued or it is working, since I've just realised that a new version is available.
Thanks,
Javier

**Comment by chaoran-chen** [comment]
HI @jpflorido, I'm sorry for the interruption! We didn't intend to discontinue it this abruptly but something went wrong just now and v1 is unfortunately at the moment not available and I'm not sure whether we will bring it back.

However, we are happy to announce LAPIS v2! It is very easy to migrate:

In case of your query, just go to https://lapis.cov-spectrum.org/open/v2/sample/aggregated?fields=pangoLineage

Otherwise, there are only two small changes:

- It’s now `/sample/aminoAcidMutations` and `/sample/nucleotideMutations` (instead of `aa-mutations` and `nuc-mutations`).
- The query parameters are now also `?aminoAcidMutations` and `?nucleotideMutations` (instead of `aaMutations` and `nucMutations`).

Sorry again and please let me know if you have trouble to use v2!

**Comment by jpflorido** [comment]
Thanks! 
I have moved to LAPIS v2 with the changes you pointed and works great.
Thanks again!
Javier
