### ISSUE TITLE
Order TSV and CSV columns as defined in config and fields

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#910]
The columns in the TSV and CSV files are currently sorted alphabetically. It would be great if it would be in the order that it was configured in the yml file.

Thanks to @theosanderson for suggesting this!

**Comment by theosanderson** [comment]
This would be great in itself. For a stretch goal one could order by the order in the yaml if no `fields` are specified, and the order in `fields` if that is specified.

**Comment by chaoran-chen** [comment]
> and the order in fields if that is specified
I'm a slightly bit hesitant about this as this would reduce the cache hits (if we cache)

**Comment by theosanderson** [comment]
Can I check on the caching concern is it your concern that:
- The full fields are A,B,C,D,E
- User X chooses "fields A,B,C"
- User Y chooses fields "C,B,A" 

and so you don't get caching. If so then I feel like in practise the selection of "A,B,C" (in any order) will be enough to miss the cache mostly, because there are so many fields that I feel like the permutations will be pretty infinite

**Comment by fengelniederhammer** [comment]
IMO this is a SILO issue. I was able to reproduce the behavior there: sending fields in arbitrary order, but SILO always returns in alphabetic order.
